namespace Spitfyr.GCP.Datastore.Adapter.Serialization
{
    public abstract class DatastoreEntity
    {
    }

    public abstract class LongIdDatastoreEntity : DatastoreEntity
    {
        [KindKey]
        public long Id { get; set; }
    }

    public class KindKeyInfo
    {
        public string KeyName { get; set; }
        public bool IsAutoGenerated { get; set; }
    }
}
