using System;

namespace Spitfyr.GCP.Datastore.Adapter.Serialization
{
    public class KindAttribute : Attribute
    {
        public string Kind { get; set; }
        public KindAttribute(string kind)
        {
            Kind = kind;
        }
    }

    public class KindKeyAttribute : Attribute
    {
        public bool IsAutoGenerated { get; set; }
        public KindKeyAttribute(bool isAutoGenerated = true)
        {
            IsAutoGenerated = isAutoGenerated;
        }
    }

    public class ExcludeIndexAttribute : Attribute
    {
    }

    [AttributeUsage(AttributeTargets.Class, Inherited = false)]
    public class InheritedEntityTypeAttribute : Attribute
    {
        public string Type { get; set; }
        public InheritedEntityTypeAttribute(string type)
        {
            Type = type;
        }
    }
}
